FROM node:20-alpine AS builder
WORKDIR /opt/server
COPY package.json .
COPY *.js .
RUN npm install

FROM node:20-alpine
RUN addgroup -S roboshop && adduser -S roboshop -G roboshop
ENV MONGO="true" \
    REDIS_URL='redis://redis:6379' \
    MONGO_URL="mongodb://mongodb:27017/users"
WORKDIR /opt/server
USER roboshop
COPY --from=builder /opt/server /opt/server
CMD ["node", "server.js"]








# FROM node:20
# WORKDIR /opt/server 

# ENV REDIS="redis://redis:6379" 
# ENV MONGO_URL="mongodb://mongodb:27017/users"
# COPY package.json .
# COPY *.js .
# RUN npm install
# CMD ["node" , "server.js"]


